---
name: Config-Model-Approx
version: 1.001
author:
  - Dominique Dumont (ddumont at cpan dot org)
abstract: Approx configuration files editor
license: lgpl
resources:
  license: http://opensource.org/licenses/lgpl-license.php
requires:
  Config::Model: 0.637
  Log::Log4perl: 0
  perl: v5.8.0
recommends:
  Config::Model::CursesUI: 0
  Config::Model::TkUI: 0
configure_requires:
  Module::Build: 0.35
provides:
  Config::Model::Approx:
    file: lib/Config/Model/Approx.pm
    version: 1.001
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
