---
abstract: 'Approx configuration files editor'
author:
  - 'Dominique Dumont (ddumont at cpan dot org)'
build_requires:
  Test::Pod: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Model-Approx
provides:
  Config::Model::Approx:
    file: lib/Config/Model/Approx.pm
    version: 1.004
recommends:
  Config::Model::CursesUI: 0
  Config::Model::TkUI: 0
requires:
  Config::Model: 1.245
  Log::Log4perl: 0
  perl: v5.8.0
resources:
  license: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
version: 1.004
